### ISSUE TITLE
關於文字辨識的訓練部份

### ISSUE THREAD

**Issue by bertrandlo** [zackexplosion/hant-counter-crawler#1]
請問這個 tesseract 有針對螢幕字體 重新訓練過嗎？

**Comment by zackexplosion** [comment]
我是直接用 https://github.com/naptha/tesseract.js/ ，沒跑過其他的訓練過設定。

如果有其他能夠提高精準度的方法還請大大賜教，謝謝 :)

**Comment by bertrandlo** [comment]
我試著開始針對 中夭粗體字訓練 fine tune 看看 如果效果比較好   我再回報～

**Comment by bertrandlo** [comment]
我正在想辦法處理看看那個字體  不過我是用 python 如果訓練OK我在把模型的檔案給你看能不能放進去那個 node module 裡面

**Comment by Boteium** [comment]
其實 tesseract (非js版) 內建預設沒這麼差, 截對文字的位置不要讓 tesseract 讀整張和做內建的預處理會快很多也準很多; 白底黑字的部份不要做二值化, 結果會比較好; 最後建議 ocr backend 別用 js

**Comment by zackexplosion** [comment]
@Boteium  這邊有做切圖，目前只截資訊卡
https://github.com/zackexplosion/YT-stream-keyword-counter/blob/master/scanner/stream-to-image.js

我有空試試看原生的tesseract，看看會不會更準一些XD

**Comment by bertrandlo** [comment]
@zackexplosion  我正在 GCE 上面針對 Noto CJK TC Black（這字型很接近寒天用的） 進行 Fine Tune 
可以繼續間段把偵測的字幕截圖 丟在 imgur 或 github 讓我測試嘛？ 這樣就不用重新抓圖了

**Comment by zackexplosion** [comment]
@bertrandlo  剛剛聊天室有人貼連結，你可以拿去用，我這邊的圖片掃完就刪掉惹
https://i.imgur.com/HvO5vL9.jpg

**Comment by bertrandlo** [comment]
謝謝^^

**Comment by bertrandlo** [comment]
@zackexplosion 
粗體字的部份初步訓練到這裡 目前字元的錯誤率( 黑底白字 約在 1.5%) 有點開始收斂變慢了
可以下載過去取代掉 tesseract tessdata 目錄裡面 chi_tra.traineddata   應該會比內建的好

https://github.com/bertrandlo/traineddata

如果後續測試彩色螢幕部份有改善  會繼續 update 目前還在看 opencv 能不能順利找出底色過濾掉
