### ISSUE TITLE
台北市市議會質詢關鍵字

### ISSUE THREAD

**Issue by yingpublic** [zackexplosion/hant-counter-crawler#2]
請問是否可以多加一個功能是監看『台北市市議會在市政質詢』時，各議員提到多少次的Korean fish關鍵字，謝謝～

**Comment by zackexplosion** [comment]
只要是YT直播畫面都可以掛著看，如果是錄影片段的話要另外分析。
『台北市市議會在市政質詢』有連結可以看嗎？

**Comment by yingpublic** [comment]
不確定這是不是官方來源：關心北市政 Youtube 頻道
https://www.youtube.com/channel/UCJWz_A8wzNsk__W2yIaDqCQ/videos

4/10
https://www.youtube.com/watch?v=8c6r2dIB2b4
https://www.youtube.com/watch?v=gsGnkQDbu0k

4/11
https://www.youtube.com/watch?v=T40Njrox2fQ
https://www.youtube.com/watch?v=SJAVS7HNsJ4

或是市長臉書訊號源
4/10
https://www.facebook.com/DoctorKoWJ/videos/2362963950395230/
https://www.facebook.com/DoctorKoWJ/videos/315167289198896/

4/11
https://www.facebook.com/DoctorKoWJ/videos/2406840889547830/
https://www.facebook.com/DoctorKoWJ/videos/279713749587139/

缺點就是，沒有把各個議員切出來的影片，沒辦法針對某議員做統計數據。

**Comment by zackexplosion** [comment]
@yingpublic  這些片段都沒字幕，沒辦法用我這個版本掃，GOOGLE做語音辨識的API 很貴XD。

我先close issue了。有其他建議歡迎繼續討論 :)

**Comment by yingpublic** [comment]
好～我找找看有沒有字幕的版本，謝謝！
